name: update data

on:
  schedule:
    - cron: "0 9 * * *" # 每天 UTC 时间早上 9 点，即北京时间下午 5 点
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run update script
        run: node ./scripts/index.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m '每日数据更新'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_DATA_TOKEN }}
